linux_task:
  container:
    image: debian
  install_script:
    - apt-get update
    - apt-get install -y tree
#    - apt-get install -y tree bash busybox dash ksh mksh posh yash zsh
#    - ln -s /bin/busybox /usr/local/bin/ash
  env:
    - ALLOW_CREATION_TO_THE_ROOT_DIRECTORY: 1
  script:
    - ./script.sh
    - ./test.sh sh

freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
  install_script:
    - pkg install -y tree coreutils
#  install_script: pkg install -y dash bash zsh ksh93 mksh oksh
  env:
    - ALLOW_CREATION_TO_THE_ROOT_DIRECTORY: 1
  script:
    - ./script.sh
    - ./test.sh sh

osx_task:
  osx_instance:
    image: catalina-base
  install_script:
    - brew install tree coreutils
  script:
    - mkdir -p ~/chroot/dev ~/chroot/var ~/chroot/tmp ~/chroot/usr
    - sudo cp -a -X /bin /sbin ~/chroot/
    - sudo cp -a -X /usr/bin /usr/lib /usr/local ~/chroot/usr/
    - sudo cp -a -X ./ ~/chroot/root
    - sudo chroot ~/chroot /root/script.sh
    - sudo chroot ~/chroot sh -c 'ALLOW_CREATION_TO_THE_ROOT_DIRECTORY=1 /root/test.sh sh'

gitbash_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    - PATH: $ProgramFiles\Git\bin;$PATH
    - MSYS: winsymlinks:nativestrict
    - ALLOW_CREATION_TO_THE_ROOT_DIRECTORY: 1
  script:
    - sh -c "./script.sh"
    - sh -c "./test.sh sh"

msys_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    - PATH: C:\tools\msys64\usr\bin;$PATH
    - MSYS: winsymlinks:nativestrict
    - ALLOW_CREATION_TO_THE_ROOT_DIRECTORY: 1
  install_script:
    - choco install -y msys2
    - pacman -S tree
  script:
    - sh -c "./script.sh"
    - sh -c "./test.sh sh"

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\cygwin\bin;$PATH
  install_script:
    - choco install -y cygwin cyg-get
    - cyg-get tree
  script:
    - sh -c "./script.sh"
