linux_task:
  container:
    image: debian
  #install_script:
  #  - apt-get update
  #  - apt-get install -y tree bash busybox dash ksh mksh posh yash zsh
  #  - ln -s /bin/busybox /usr/local/bin/ash
  script:
    - mkdir -p chroot/bin   && mount --bind /bin   chroot/bin
    - mkdir -p chroot/usr   && mount --bind /usr   chroot/usr
    - mkdir -p chroot/lib   && mount --bind /lib   chroot/lib
    - mkdir -p chroot/lib64 && mount --bind /lib64 chroot/lib64
    - mkdir -p chroot/etc   && mount --bind /etc   chroot/etc
    - chroot chroot ./script.sh

#freebsd_task:
#  freebsd_instance:
#    image_family: freebsd-12-1
#  install_script: pkg install -y dash bash zsh ksh93 mksh oksh
#  script:
#    - ./script.sh
#
#osx_task:
#  osx_instance:
#    image: catalina-base
#  script:
#    - ./script.sh
#
#gitbash_task:
#  windows_container:
#    image: cirrusci/windowsservercore:2019
#    os_version: 2019
#  env:
#    PATH: $ProgramFiles\Git\bin;$PATH
#  script:
#    - bash -c "./script.sh"
#
#msys_task:
#  windows_container:
#    image: cirrusci/windowsservercore:2019
#    os_version: 2019
#  env:
#    PATH: C:\tools\msys64\usr\bin;$PATH
#  install_script:
#    - choco install -y msys2
#  script:
#    - bash -c "./script.sh"
#
#cygwin_task:
#  windows_container:
#    image: cirrusci/windowsservercore:2019
#    os_version: 2019
#  env:
#    PATH: C:\tools\cygwin\bin;$PATH
#  install_script:
#    - choco install -y cygwin cyg-get
#  script:
#    - bash -c "./script.sh"
#