gitbash_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $ProgramFiles\Git\bin;$PATH
  script:
    - where bash
    - bash -c "script.sh"

msys_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\msys64\usr\bin;$PATH
  install_script:
    - choco install -y msys2
  script:
    - where bash
    - bash -c "contrib/all.sh shellspec"

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\cygwin\bin;$PATH
  install_script:
    - choco install -y cygwin cyg-get
  script:
    - where bash
    - bash -c 'contrib/all.sh shellspec'
