linux_task:
  container:
    image: debian
  script:
    - which bash git
    - git config -l
    - ./script.sh

freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-1
  install_script: pkg install -y dash bash zsh ksh93 mksh oksh
  script:
    - which bash git
    - git config -l
    - ./script.sh

osx_task:
  osx_instance:
    image: catalina-base
  script:
    - which bash git
    - git config -l
    - ./script.sh

gitbash_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $ProgramFiles\Git\bin;$PATH
  script:
    - where bash git
    - bash -c "git config -l"
    - bash -c "./script.sh"

msys_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\msys64\usr\bin;$PATH
  install_script:
    - choco install -y msys2
  script:
    - where bash git
    - bash -c "git config -l"
    - bash -c "./script.sh"

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\cygwin\bin;$PATH
  install_script:
    - choco install -y cygwin cyg-get
  script:
    - where bash git
    - bash -c "git config -l"
    - bash -c "git config --global core.autoCRLF false"
    - bash -c "git reset --hard"
    - bash -c "./script.sh"
