#CirrusCI_task:
#  freebsd_instance:
#    matrix:
#      - image: freebsd-11-2-release-amd64
#      - image: freebsd-12-0-release-amd64
#  script:
#    - uname -a
#    - echo ok

CirrusCI_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    - PATH: $PATH;$ProgramFiles\Git\bin
  script:
    - ver
    - set
    - where bash
    - bash -c 'ls -al'
